name: ribosome
version: 0.1.2.0
synopsis: api extensions for nvim-hs
description: Please see the README on GitHub at <https://github.com/tek/proteome-hs>
github: "tek/ribosome-hs"
license: MIT
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2018 Torsten Schmits"
category: Neovim
build-type: Simple

dependencies:
- base >= 4.7 && < 5
- unliftio
- unliftio-core
- nvim-hs
- utf8-string
- split
- time
- containers
- filepath
- resourcet
- mtl
- deepseq
- messagepack
- text
- pretty-terminal
- ansi-terminal
- hslogger
- directory
- process
- stm
- lens
- data-default
- MissingH
- aeson
- bytestring
- transformers
- safe
- either
- prettyprinter
- prettyprinter-ansi-terminal

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeSynonymInstances
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs: lib

tests:
  ribosome-unit:
    main: SpecMain.hs
    source-dirs: test/u
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ribosome
    - HTF
  ribosome-functional:
    main: SpecMain.hs
    source-dirs: test/f
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ribosome
    - HTF
