resolver: lts-16.16
packages:
- modules/core
- modules/test
- .
# - ../cornea
# - ../chiasma
# - ../nvim-hs
extra-deps:
- pretty-terminal-0.1.0.0
- posix-pty-0.2.1.1
- fuzzy-0.1.0.0
- messagepack-0.5.4
- github: neovimhaskell/nvim-hs
  commit: 6eb110f11a3875da1be9415515014d574834391b
- github: tek/cornea
  commit: 43c649fa064fd5c90047a76829f353c51b3cde0a
- github: tek/chiasma
  commit: 25578d92b19beba962f8e163805a42da94715a8e
