resolver: lts-13.27
packages:
- modules/core
- modules/test
- .
# - ../cornea
# - ../chiasma
# - ../nvim-hs
extra-deps:
- base-noprelude-4.12.0.0
- pretty-terminal-0.1.0.0
- posix-pty-0.2.1.1
- fuzzy-0.1.0.0
- messagepack-0.5.4
- github: neovimhaskell/nvim-hs
  commit: c20824c0f98c7dcb64d6368b187db49fd0e10a4e
- github: tek/cornea
  commit: 43c649fa064fd5c90047a76829f353c51b3cde0a
- github: tek/chiasma
  commit: 25578d92b19beba962f8e163805a42da94715a8e
