resolver: lts-12.26
packages:
- modules/core
- modules/test
- .
- ../cornea
- ../chiasma
- ../nvim-hs
extra-deps:
- base-noprelude-4.11.1.0
- pretty-terminal-0.1.0.0
- posix-pty-0.2.1.1
# - cornea-0.1.0.0
# - chiasma-0.1.0.0
