name: ribosome
version: 0.3.0.0
synopsis: api extensions for nvim-hs
description: Please see the README on GitHub at <https://github.com/tek/ribosome-hs>
github: "tek/ribosome-hs"
license: OtherLicense
license-file: LICENSE
author: "Torsten Schmits"
maintainer: "tek@tryp.io"
copyright: "2019 Torsten Schmits"
category: Neovim
build-type: Simple

dependencies:
- MissingH
- aeson
- ansi-terminal
- base-noprelude >= 4.7 && < 5
- bytestring
- chiasma
- composition
- composition-extra
- conduit
- containers
- cornea
- data-default
- deepseq
- directory
- either
- exceptions
- filepath
- free
- hslogger
- lens
- lifted-base
- messagepack
- monad-control
- mtl
- nvim-hs
- path
- path-io
- pretty-terminal
- prettyprinter
- prettyprinter-ansi-terminal
- process
- relude
- resourcet
- safe
- split
- stm
- stm-chans
- stm-conduit
- template-haskell
- text
- th-abstraction
- time
- transformers
- transformers-base
- typed-process
- unix
- unliftio
- unliftio-core
- utf8-string

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- UnicodeSyntax
- ViewPatterns

library:
  source-dirs: lib
  other-modules:
    - Prelude
