---
name: 'push'

on:
  push:
    branches:
      - '**'

jobs:
  release:
    name: 'Test and push to Cachix'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            extra-substituters = https://tek.cachix.org
            extra-trusted-public-keys = tek.cachix.org-1:+sdc73WFq8aEKnrVv5j/kuhmnW2hQJuqdPJF5SnaCBk=
      - uses: cachix/cachix-action@v12
        with:
          name: tek
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - name: 'build'
        run: nix flake check
      - name: 'template test'
        run: nix run .#template-test
